"""Dify Workflow DSL generator for the workbench API adapter."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_DIFY_DSL_PATH = Path("docs/integrations/dify/literary-workbench-reviewer.workflow.yml")


@dataclass(frozen=True)
class DifyDslOptions:
    output: Path = DEFAULT_DIFY_DSL_PATH
    app_name: str = "文学工程审稿台"
    api_base: str = "http://127.0.0.1:8765"
    dsl_version: str = "0.6.0"
    default_mode: str = "full-cycle"
    default_scene: str = "scenes/scene_0001.yaml"
    default_chapter_id: str = "chapter_0001"


@dataclass(frozen=True)
class DifyDslResult:
    output_path: Path
    app_name: str
    api_base: str
    node_count: int
    endpoint_count: int


def build_dify_workflow_dsl(options: DifyDslOptions) -> DifyDslResult:
    output_path = options.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = render_dify_workflow_dsl(options)
    output_path.write_text(content, encoding="utf-8")
    return DifyDslResult(
        output_path=output_path,
        app_name=options.app_name,
        api_base=options.api_base,
        node_count=4,
        endpoint_count=2,
    )


def render_dify_workflow_dsl(options: DifyDslOptions) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    api_base = _yaml_string(options.api_base.rstrip("/"))
    app_name = _yaml_string(options.app_name)
    dsl_version = _yaml_string(options.dsl_version)
    default_mode = _yaml_string(options.default_mode)
    default_scene = _yaml_string(options.default_scene)
    default_chapter_id = _yaml_string(options.default_chapter_id)
    return f"""# Generated by literary-engineering-workbench dify-dsl.
# Generated at: {generated_at}
#
# Import target: Dify Workflow app, DSL {options.dsl_version}.
# This is an import-safe starter: import it first, then add Human Input /
# approval nodes in the Dify UI if your workspace supports them. Creative
# decisions should enter through /director/chat; lower-level workflow endpoints
# are for debugging and specialist tools.

app:
  description: "Creative director console for Literary Engineering Workbench."
  icon: "\U0001F4DA"
  icon_background: "#F4F1EA"
  icon_type: emoji
  mode: workflow
  name: {app_name}
  use_icon_as_answer_icon: false
kind: app
version: {dsl_version}
dependencies: []

workflow:
  conversation_variables: []
    environment_variables:
    - description: "Literary Engineering Workbench API base URL."
      id: "env_workbench_api_base"
      name: WORKBENCH_API_BASE
      selector:
        - env
        - WORKBENCH_API_BASE
      value: {api_base}
      value_type: string
    - description: "Optional API token. Leave empty when serve-api runs without --api-token."
      id: "env_workbench_api_token"
      name: WORKBENCH_API_TOKEN
      selector:
        - env
        - WORKBENCH_API_TOKEN
      value: ""
      value_type: secret
  features:
    file_upload:
      enabled: false
      image:
        enabled: false
      number_limits: 3
      allowed_file_extensions: []
      allowed_file_types: []
      allowed_file_upload_methods:
        - local_file
        - remote_url
    opening_statement: ""
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ""
      voice: ""
  graph:
    edges:
      - data:
          isInIteration: false
          isInLoop: false
          sourceType: start
          targetType: http-request
        id: "1000000000000-source-1000000000001-target"
        selected: false
        source: "1000000000000"
        sourceHandle: source
        target: "1000000000001"
        targetHandle: target
        type: custom
        zIndex: 0
      - data:
          isInIteration: false
          isInLoop: false
          sourceType: http-request
          targetType: http-request
        id: "1000000000001-source-1000000000002-target"
        selected: false
        source: "1000000000001"
        sourceHandle: source
        target: "1000000000002"
        targetHandle: target
        type: custom
        zIndex: 0
      - data:
          isInIteration: false
          isInLoop: false
          sourceType: http-request
          targetType: end
        id: "1000000000002-source-1000000000003-target"
        selected: false
        source: "1000000000002"
        sourceHandle: source
        target: "1000000000003"
        targetHandle: target
        type: custom
        zIndex: 0
    nodes:
      - data:
          desc: ""
          selected: false
          title: "Start"
          type: start
          variables:
            - label: "Project root"
              max_length: 4096
              required: true
              type: text-input
              variable: project_root
            - default: "把项目推进到下一轮创作开发，请由创作总监决定内部工作流。"
              label: "Creative direction"
              max_length: 4096
              required: true
              type: paragraph
              variable: creative_direction
            - default: auto
              label: "Agent provider"
              options:
                - auto
                - http-chat
                - dry-run
              required: true
              type: select
              variable: provider
            - default: "true"
              label: "Auto execute"
              options:
                - "true"
                - "false"
              required: true
              type: select
              variable: auto_execute
            - default: "true"
              label: "Agent task sidecars"
              options:
                - "true"
                - "false"
              required: true
              type: select
              variable: agent_tasks
        height: 120
        id: "1000000000000"
        position:
          x: 80
          y: 260
        positionAbsolute:
          x: 80
          y: 260
        selected: false
        sourcePosition: right
        targetPosition: left
        type: custom
        width: 260
      - data:
          authorization:
            type: no-auth
          body:
            data:
              - id: body-project-root
                key: project_root
                type: string
                value: "{{{{#1000000000000.project_root#}}}}"
              - id: body-message
                key: message
                type: string
                value: "{{{{#1000000000000.creative_direction#}}}}"
              - id: body-provider
                key: provider
                type: string
                value: "{{{{#1000000000000.provider#}}}}"
              - id: body-auto-execute
                key: auto_execute
                type: string
                value: "{{{{#1000000000000.auto_execute#}}}}"
              - id: body-agent-tasks
                key: agent_tasks
                type: string
                value: "{{{{#1000000000000.agent_tasks#}}}}"
            type: json
          desc: ""
          headers: |-
            Content-Type: application/json
            Authorization: Bearer {{{{#env.WORKBENCH_API_TOKEN#}}}}
          method: post
          params: ""
          retry_config:
            retry_enabled: false
          selected: false
          timeout:
            connect: 10
            read: 300
            write: 30
          title: "Run creative director"
          type: http-request
          url: "{{{{#env.WORKBENCH_API_BASE#}}}}/director/chat"
        height: 120
        id: "1000000000001"
        position:
          x: 390
          y: 260
        positionAbsolute:
          x: 390
          y: 260
        selected: false
        sourcePosition: right
        targetPosition: left
        type: custom
        width: 260
      - data:
          authorization:
            type: no-auth
          body:
            data: []
            type: none
          desc: ""
          headers: |-
            Authorization: Bearer {{{{#env.WORKBENCH_API_TOKEN#}}}}
          method: get
          params: ""
          retry_config:
            retry_enabled: false
          selected: false
          timeout:
            connect: 10
            read: 120
            write: 10
          title: "Read director report"
          type: http-request
          url: "{{{{#env.WORKBENCH_API_BASE#}}}}/workflow/artifact?project_root={{{{#1000000000000.project_root#}}}}&path={{{{#1000000000001.body.data.report#}}}}"
        height: 120
        id: "1000000000002"
        position:
          x: 700
          y: 260
        positionAbsolute:
          x: 700
          y: 260
        selected: false
        sourcePosition: right
        targetPosition: left
        type: custom
        width: 260
      - data:
          desc: ""
          outputs:
            - value_selector:
                - "1000000000001"
                - body
              variable: director_response
            - value_selector:
                - "1000000000001"
                - status_code
              variable: director_status_code
            - value_selector:
                - "1000000000002"
                - body
              variable: director_report_response
            - value_selector:
                - "1000000000002"
                - status_code
              variable: report_status_code
          selected: false
          title: "End"
          type: end
        height: 100
        id: "1000000000003"
        position:
          x: 1010
          y: 260
        positionAbsolute:
          x: 1010
          y: 260
        selected: false
        sourcePosition: right
        targetPosition: left
        type: custom
        width: 260
    viewport:
      x: 0
      y: 0
      zoom: 0.8
"""


def _yaml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
